basePath: /
host: localhost
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: https://github.com/jubarodrigo/go-code-challenge
  description: This is the Go server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Go Code Challenge API
  version: "1.0"
paths: {}
swagger: "2.0"
